# Generated by Django 4.2.2 on 2023-07-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='city_info',
        ),
    ]
